---
title: 
output:
  html_fragment
    
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
### **Climate Metrics Explorer**
<br>
Conservation planners and practitioners increasingly wonder how they should revise conservation strategies in the face of the unprecedented threat to biodiversity from climate change. One key step is to consider the relatively consistent spatial patterns that characterize the "geography of climate exposure and resilience". These patterns are often generated by the interaction of global climate systems with regional topography, but may also be influenced by biogeographic processes and other factors. A qualitative understanding of these patterns can help planners craft conservation strategies that are more resilient to uncertainty regarding the future intensity of climate change.
<br>
<br>
In this **Climate Metrics Explorer**, users can view maps of key metrics that are used to assess landscape-level climate resilience and vulnerability, and can generate reports summarizing and mapping these metrics by watershed. In addition to the information contained in each report, see this app's **Climate Metrics Tour** for more information on what each of these metrics represent and why they are relevant to climate adaptation planning. For more information on patterns of climate resilience within North American protected areas and other management areas, see this app's **Protected Area Tour** and **Protected Area Explorer** modules. Spatial data shown in this Explorer are freely available at the links below.

  
  **Climate Resilience Metric:**
  
  * [Climatic dissimilarity](https://adaptwest.databasin.org/pages/climatic-dissimilarity) 
  * [Forward and backward climatic velocity](https://adaptwest.databasin.org/pages/adaptwest-velocitywna)
  * [Topodiversity](https://adaptwest.databasin.org/pages/environmental-diversity-north-america)
  * [Biotic velocity](https://adaptwest.databasin.org/pages/climatic-macrorefugia-for-trees-and-songbirds)
  * [Climate connectivity](https://adaptwest.databasin.org/pages/climate-connectivity-north-america)
  * [Aboveground forest carbon](http://globbiomass.org/wp-content/uploads/GB_Maps/Globbiomass_global_dataset.html)
  * [Soil carbon](https://data.isric.org/geonetwork/srv/eng/catalog.search#/metadata/c02ddf8b-cbfb-4533-a9c3-7bf0790fd042)
  * [Intactness (the inverse of landuse intensity)](https://figshare.com/articles/Global_Human_Modification/7283087)
  


