---
title: 
output:
  html_fragment
    
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
### **Protected Area Explorer**
<br>
Expansion of the global protected area network and more effective placement of new protected areas are increasingly seen as critical measures to counter threats arising from the twin crises of accelerating climate change and species extinction. A key step in increasing the effectiveness of protected area networks is a better understanding of how threats to biodiversity from climate change impact the ability of protected areas to sustain species and ecosystems.
<br>
<br>
The goal of the **Protected Areas Explorer** is to familiarize conservation practitioners with the landscape-level characteristics that can help in evaluating climate-change-related threats to the integrity of protected areas, and the role such areas may play in enhancing the climate resilience of the broader region.
<br>
<br>
In this **Protected Area Explorer**, users can view maps of key metrics that are used to assess landscape-level climate resilience and vulnerability, and can generate reports summarizing and mapping these metrics by management area. We consider landscape metrics related to both climate mitigation (safeguarding ecosystems in their ability to store above- and below-ground carbon) and climate adaptation and resilience (for example, the ability of an area to provide climate refugia). For more information on patterns of climate resilience within North American protected areas and other management areas, see this app's **Protected Area Tour** module. In addition to the information contained in each report, see this app's **Climate Metrics Tour** for more information on what each of these metrics represent and why they are relevant to climate adaptation planning. Spatial data shown in this Explorer are freely available at the links below.

  
  **Climate Resilience Metric:**
  
  * [Climatic dissimilarity](https://adaptwest.databasin.org/pages/climatic-dissimilarity) 
  * [Forward and backward climatic velocity](https://adaptwest.databasin.org/pages/adaptwest-velocitywna)
  * [Topodiversity](https://adaptwest.databasin.org/pages/environmental-diversity-north-america)
  * [Biotic velocity](https://adaptwest.databasin.org/pages/climatic-macrorefugia-for-trees-and-songbirds)
  * [Climate connectivity](https://adaptwest.databasin.org/pages/climate-connectivity-north-america)
  * [Aboveground forest carbon](http://globbiomass.org/wp-content/uploads/GB_Maps/Globbiomass_global_dataset.html)
  * [Soil carbon](https://data.isric.org/geonetwork/srv/eng/catalog.search#/metadata/c02ddf8b-cbfb-4533-a9c3-7bf0790fd042)
  * [Intactness (the inverse of landuse intensity)](https://figshare.com/articles/Global_Human_Modification/7283087)
